### ISSUE TITLE
Контейнер не работает

### ISSUE THREAD

**Issue by TiGR** [yandex-money/yandex-money-kassa-example#10]
Если пытаться сделать как есть - контейнер собирается, запускается, но по localhost:8080 тишина. Если изменить `image` в `docker-compose.yml` на `million12/nginx-php:php-55` и пересобрать контейнер, то начинает работать.

**Comment by raymank26** [comment]
Добрый день,

Действительно, последний образ похоже сломан. Изменил на `million12/nginx-php:php-55`
