### ISSUE TITLE
Форма оплаты для ИП физ.лиц 

### ISSUE THREAD

**Issue by coffebar** [yandex-money/yandex-money-kassa-example#7]
Форма в paymentForm.html подходит для физ.лиц?

Где брать параметр scid?

**Comment by boobooking** [comment]
Параметр scid выдают под каждое подключение к Кассе при заполнении анкеты. Приходит в письме от Яндекса вместе с shop_id.

**Comment by coffebar** [comment]
Спасибо за ответ
